
export enum PropertyType {
	SCOOTER  = 'SCOOTER',
	SPORT  = 'SPORT',
	CRUISER  = 'CRUISER',
	TOURING = 'TOURING',
}

export enum PropertyCondition {
	NEW = 'NEW',
	USED = 'USED',
}

export enum PropertyBrand {
  SUZUKI = 'SUZUKI',
  HONDA = 'HONDA',
  YAMAHA = 'YAMAHA',
  KAWASAKI = 'KAWASAKI',
  DUCATI = 'DUCATI',
  BMW = 'BMW',
  HARLEY_DAVIDSON = 'HARLEY_DAVIDSON',
}

export enum PropertyStatus {
	HOLD = 'HOLD',
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	DELETE = 'DELETE',
}

export enum PropertyLocation {
	TASHKENT = 'TASHKENT',
	ANDIJAN = 'ANDIJAN',
	BUKHARA = 'BUKHARA',
	FERGANA = 'FERGANA',
	JIZZAKH = 'JIZZAKH',
	KHOREZM = 'KHOREZM',
	NAMANGAN = 'NAMANGAN',
	NAVOI = 'NAVOI',
	KASHKADARYA = 'KASHKADARYA',
	SAMARKAND = 'SAMARKAND',
	SIRDARYA = 'SIRDARYA',
	SURKHANDARYA = 'SURKHANDARYA',
	KARAKALPAKSTAN = 'KARAKALPAKSTAN',
}


